---
apps:
  - { id: '0001',
  admin: diego@diegoneves.eti.br,
  dominio: site1.gdg.com.br,
  apphost: 555.555.555.555,
  dbhost: 555.555.555.444,
  dbname: gdg-site-1,
  dbuser: sa_gdg-site-1,
  dbpass: bIPf48nUplke34p,
  wp_auth_key: B1P9l8OID5K7b97O7F45oLaxr,
  wp_secure_auth_key: bIjidIM9k4cRQnXNV2bp261yo,
  wp_logged_in_key: 13w12155ejOmT2O33IBN95u4u,
  wp_nonce_key: 184jY2k760U8674588z0grs6Q,
  wp_auth_salt: ls4397gruzVXP729ao4mht0Ph,
  wp_secure_auth_salt: rU0qYZ0T9L4NNI6914Yn8K63e,
  wp_logged_in_salt: N69zsxunT5h8zd7dTxwB21zWO,
  wp_nonce_salt: 529YF370r8gF8NAJ646uwqN1M }

  - { id: '0002',
  admin: diego@diegoneves.eti.br,
  dominio: site2.gdg.com.br,
  apphost: 555.555.555.555,
  dbhost: 555.555.555.444,
  dbname: gdg-site-1,
  dbuser: sa_gdg-site-1,
  dbpass: Y64X90eVR5g833I,
  wp_auth_key: 5k98yJ15W48999PTX2L44aT8H,
  wp_secure_auth_key: 2B57ZqPb5DHujSleR65NM4cdI,
  wp_logged_in_key: emybEzEiMus7yqMCvnSxWRPhi,
  wp_nonce_key: 03d7y8Pb292n62W043w9e2V5x,
  wp_auth_salt: 6odMo1zZ6GKc0HLfNL110RHGY,
  wp_secure_auth_salt: AP46pKBnm40Hu75CgRCHK5r6l,
  wp_logged_in_salt: L3l5fg6KU028Z5L7WUf26CX5R,
  wp_nonce_salt: 1949qYs9pzvthu9k77cHRTRzK }